preferredBranch: 'develop'
exclude:
  - branch: dont-switch
  - branch: another-dont-switch-branch
  - label: ignore-me
  - label: ignore-me-always
# Comment to post when switching the branch
switchComment: >
  @{{author}}, sorry for interrupting. Just changed the base branch to `{{preferredBranch}}`.
