preferredBranch: 'develop'
exclude:
  - branch: dont-switch
  - branch: another-dont-switch-branch
  - label: ignore-me
  - label: ignore-me-always
# Comment to post when switching the branch
switchComment: >
  thanks @{{author}} for your contributions. You are the best. :1st_place_medal:
