name: Blobs Upgrader

on:
  push:
    branches:
    - master

jobs:
  upgrade:
    name: Upgrade bosh blobs
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkout submodules
        run: git submodule update --init --recursive
      - name: Download BOSH CLI
        uses: docker://dpb587/gget
        with:
          args: --exec github.com/cloudfoundry/bosh-cli "bosh=bosh-cli-*-linux-amd64"
      - name: Install BOSH CLI
        run: |
          mkdir -p  $GITHUB_WORKSPACE/bin
          mv ./bosh $GITHUB_WORKSPACE/bin/
          echo "::add-path::$GITHUB_WORKSPACE/bin"
      - name: BOSH help
        run: bosh --help
